language: c

before_install:
  - sudo apt-get install -y cppcheck

script:
  - cd q1
  - mkdir -p bin
  - mkdir -p obj
  - cppcheck ./src/solution.c -I./include
  - mv test/testq1.db test/part2_rtree.db
  - make test
